# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
  - link: blocks/about
    label: About
  - path: page/how-to-help
  - label: Home
    title: This is the <b>first<b> menu item.
    class: homepage
    submenu:
        - label: Sub 1
          link: entry/29
        - label: Sub 2
          class: menu-item-class
          link: entry/30
#        - label: Sub 3
#          link: entry/31
#        - label: Sub 4
#          class: sub-class
#          link: page/32
  - label: All pages
    link: /pages
#  - label: The Bolt site
#    link: https://bolt.cm
#    class: bolt-site
#    title: Visit the excellent Bolt website!

social:
    - path: page/donate
      class: button
    - link: https://facebook.com/firulay-mimi
      class: social
      label: facebook
    - link: https://instagram.com/firulay-mimi
      class: social
      label: instagram